# fly.toml app configuration file generated for project-assistant on 2026-04-28T16:30:49+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-assistant'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]

[deploy]
#  release_command = './bin/rails db:schema:load'
  release_command = './bin/rails db:prepare'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
  cpu_kind = "shared"

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = 10000
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false
