nr: "Not Required"
cable:
  constructions:
    core: 1
    pair: 2
    triple: 3
tag:
  serial_digits: 4
  separator: "-"
document:
  serial_digits: 5
  separator: "-"
ingress_protection:
  first_digit:
    no_protection: 0
    solid_objects_50mm: 1
    solid_objects_12mm: 2
    solid_objects_2_5mm: 3
    solid_objects_1mm: 4
    dust_protected: 5
    dust_tight: 6
  second_digit:
    no_protection: 0
    dripping_water: 1
    dripping_water_tilted: 2
    spraying_water: 3
    splashing_water: 4
    water_jets: 5
    powerful_water_jets: 6
    temporary_immersion: 7
    continuous_immersion: 8
    high_pressure_water_jets: 9
si_prefix:
  -18: "a"
  -15: "f"
  -12: "p"
  -9: "n"
  -6: "μ"
  -3: "m"
  0: ""
  3: "k"
  6: "M"
  9: "G"
  12: "T"
  15: "P"
  18: "E"