# Standard engineering disciplines available in the system
# These will be available to all projects
#
# Fields:
#   label:      Short 1-5 character code for display (project customizable)
#   prefix_schema: Schema for tag/document numbering
#   sort_order: Display order in UI (lower numbers first)
#   required_role: Default required role for content creation (:designer, :checker, :approver, :controller or nil)

disciplines:

  Process:
    label: P
    prefix_schema: { name: 'default' }
    sort_order: 30
    required_role: :designer
    catalog_required_role: :custodian

  Electrical:
    label: E
    prefix_schema: { name: 'default' }
    sort_order: 10
    required_role: :designer
    catalog_required_role: :custodian

  Instrument:
    label: J
    prefix_schema: { name: 'isa51' }
    sort_order: 40
    required_role: :designer
    catalog_required_role: :custodian

  InformationTechnology:
    label: IT
    prefix_schema: { name: 'default' }
    sort_order: 50
    required_role: :designer
    catalog_required_role: :custodian

  Mechanical:
    label: M
    prefix_schema: { name: 'default' }
    sort_order: 60
    required_role: :designer
    catalog_required_role: :custodian

  Piping:
    label: PIP
    prefix_schema: { name: 'default' }
    sort_order: 70
    required_role: :designer
    catalog_required_role: :custodian

  Civil:
    label: C
    prefix_schema: { name: 'default' }
    sort_order: 80
    required_role: :designer
    catalog_required_role: :custodian