# Standard engineering disciplines available in the system
# These will be available to all projects
#
# Fields:
#   label:      Short 1-5 character code for display (project customizable)
#   prefix_schema: Schema for tag/document numbering
#   sort_order: Display order in UI (lower numbers first)
#   required_role: Default required role for content creation (:designer, :checker, :approver, :controller or nil)

disciplines:

  Administration:
    label: A
    prefix_schema: { name: 'default' }
    sort_order: 10
    required_role: :designer

  Architecture:
    label: B
    prefix_schema: { name: 'default' }
    sort_order: 20
    required_role: :designer

  DocumentControl:
    label: DC
    prefix_schema: { name: 'default' }
    sort_order: 25
    required_role: :document_controller

  Process:
    label: P
    prefix_schema: { name: 'default' }
    sort_order: 30
    required_role: :designer

  Electrical:
    label: E
    prefix_schema: { name: 'default' }
    sort_order: 10
    required_role: :designer

  Instrument:
    label: J
    prefix_schema: { name: 'isa51' }
    sort_order: 40
    required_role: :designer

  InformationTechnology:
    label: IT
    prefix_schema: { name: 'default' }
    sort_order: 50
    required_role: :designer

  Mechanical:
    label: M
    prefix_schema: { name: 'default' }
    sort_order: 60
    required_role: :designer

  Piping:
    label: PIP
    prefix_schema: { name: 'default' }
    sort_order: 70
    required_role: :designer

  Civil:
    label: C
    prefix_schema: { name: 'default' }
    sort_order: 80
    required_role: :designer