electrical:
  loadable:
    - Switchboard
    - SocketCct
    - LightCct
    - Motor
    - Heater
    - Equipment
  connect_options:
    - Circuit
    - Demand
  phase_designation:
    "L1":       1
    "L2":       2
    "L3":       3
    "ALL":      4
  protection:
    device:
      "MCB":  1
      "MCCB": 2
    curve:
      "A":  1
      "B":  2
      "C":  3
      "D":  4
      "K":  5
    elcb:
      "None": 1
      "20mA": 2
      "30mA": 3
      "other":  4
  mcb_rating:
    - 1
    - 2
    - 4
    - 6
    - 10
    - 16
    - 20
    - 25
    - 32
    - 40
    - 50
    - 63
  conductor_csa:
    - 0.5
    - 0.75
    - 1.0
    - 1.5
    - 2.5
    - 4.0
    - 6.0
    - 10.0
    - 16.0
    - 25.0
    - 35.0
    - 50.0
    - 70.0
    - 95.0
    - 120.0
    - 150.0
    - 185.0
    - 240.0
    - 300.0
    - 400.0
    - 500.0
  conductor_materials:
    "Cu": 0  # Copper
    "Al": 1  # Aluminium 
  insulation_materials:
    "PVC": 0π
    "XLPE": 1
    "LSZH": 2  # Low Smoke Zero Halogen
    "EPR": 3   # Ethylene Propylene Rubber
    "PUR": 4   # Polyurethane
  armour_materials:
    "SWA": 0    # Steel Wire Armour
    "STA": 1    # Steel Tape Armour
    "AWA": 2    # Aluminium Wire Armour
    "ATA": 3    # Aluminium Tape Armour
    "GSWA": 4   # Galvanized Steel Wire Armour
  voltage_ratings:
    other: 0
    "300/500V": 1
    "450/750V": 2
    "600/1000V": 3
    "1.9/3.3kV": 4
    "3.3/6.6kV": 5
    "6.6/11kV": 6
    "11/33kV": 7
    "33/66kV": 8
    "66/132kV": 9
    "132/220kV": 10
  temperature_rating:
    - "60˚C"
    - "75˚C"
    - "90˚C"
  load_basis:
    summation:      1
    power_pf:       2
    vector_pf:      3
    current_pf:     4
    current_power:  5
  load_configuration:
    dc:             1
    one:            2
    two_120:        3
    two_180:        4
    three_3c:       5
    three_4c:       6
  supply:
    "220V":             220.0
    "240V":             240.0
    "400V":             400.0
    "415V":             415.0
    "690V":             690.0
    "1kV":              1000.0
  ingress_protection:
    first_digit:
      no_protection: 0
      solid_objects_50mm: 1
      solid_objects_12mm: 2
      solid_objects_2_5mm: 3
      solid_objects_1mm: 4
      dust_protected: 5
      dust_tight: 6
    second_digit:
      no_protection: 0
      dripping_water: 1
      dripping_water_tilted: 2
      spraying_water: 3
      splashing_water: 4
      water_jets: 5
      powerful_water_jets: 6
      temporary_immersion: 7
      continuous_immersion: 8
      high_pressure_water_jets: 9
  motor_type:
    other: 0
    induction: 1
    synchronous: 2
    dc: 3
    servo: 4
    stepper: 5
    brushless_dc: 6
    universal: 7
  frame_size:
    "63": 63
    "71": 71
    "80": 80
    "90": 90
    "100": 100
    "112": 112
    "132": 132
    "160": 160
    "180": 180
    "200": 200
    "225": 225
    "250": 250
    "280": 280
    "315": 315
    "355": 355
    "400": 400
    "450": 450
    "500": 500
    "560": 560
    "630": 630