prefix_parser_keys:
  - default
  - isa51
  - dim1
  - dim2
prefix_schemata:
  default:
    type: 'default'
  isa51:
    type: 'isa51'
    measured_variable:
      'A': 'Analysis'
      'B': 'Burner, combustion'
      'C': 'User''s choice'
      'D': 'User''s choice'
      'E': 'Voltage'
      'F': 'Flow rate'
      'G': 'User''s choice'
      'H': 'Hand'
      'I': 'Current (electrical)'
      'J': 'Power'
      'K': 'Time, time schedule'
      'L': 'Level'
      'M': 'User''s choice'
      'N': 'User''s choice'
      'O': 'User''s choice'
      'P': 'Pressure, vacuum'
      'Q': 'Quantity'
      'R': 'Radiation'
      'S': 'Speed, frequency'
      'T': 'Temperature'
      'U': 'Multivariable'
      'V': 'Vibration, mechanical analyses'
      'W': 'Weight, force'
      'X': 'Unclassified'
      'Y': 'Event, state or presence'
      'Z': 'Position, dimension'

    # Modifiers
    modifier:
      'D': 'Differential'
      'F': 'Ration (fraction)'
      'J': 'Scan'
      'K': 'Time rate of change'
      'M': 'Momentary'
      'Q': 'Integrate, totalizer'
      'S': 'Safety'
      'X': 'X-axis'
      'Y': 'Y-axis'
      'Z': 'Z-axis'

    # Readout or Passive Functions
    readout_function:
      'A': 'Alarm'
      'B': 'User''s choice'
      'E': 'Sensor (primary element)'
      'G': 'Glass, viewing device'
      'I': 'Indication'
      'L': 'Light'
      'N': 'User''s choice'
      'O': 'Orifice, restriction'
      'P': 'Point (test connection)'
      'R': 'Record'
      'U': 'Multifunction'
      'W': 'Well'
      'X': 'Unclassified'

    # Output Functions
    output_function:
      'B': 'User''s choice'
      'C': 'Control'
      'K': 'Control Station'
      'N': 'User''s choice'
      'S': 'Switch'
      'T': 'Transmit'
      'U': 'Multifunction'
      'V': 'Valve, damper, louver'
      'X': 'Unclassified'
      'Y': 'Relay, compute, convert'
      'Z': 'Driver, actuator'

    # Modifier Functions
    modifier_function:
      'B': 'User''s choice'
      'H': 'High'
      'HH': 'High high'
      'L': 'Low'
      'LL': 'Low low'
      'M': 'Middle, intermediate'
      'N': 'User''s choice'
      'U': 'Multifunction'
      'X': 'Unclassified'
  dim1:
    type: 'dim1'
    prefix:
      'A': 'Package'
      'B': 'Building'
      'EC': 'Electrical Cable'
      'EH': 'Electrical Heater'
      'EL': 'Light Circuit'
      'EM': 'Motor'
      'ES': 'Socket Circuit'
      'EX': 'Switchboard'
      'PM': 'Pump Motor'
  dim2:
    type: 'dim2'
    part1:
      'G': 'Generator'
      'H': 'Heater'
      'P': 'Pump'
      'S': 'Switchboard'
      'T': 'Transformer'
      'V': 'Valve'
      'P': 'Pump'
      'K': 'Fan'
    part2:
      'M': 'Motor'
      'B': 'Box'
  alternate_inst:
    type: 'isa51'
    measured_variable:
      'A': 'Analysis'
      'B': 'Burner, combustion'
      'C': 'User''s choice'
      'D': 'User''s choice'
      'E': 'Voltage'
      'F': 'Flow rate'
      'G': 'User''s choice'
      'H': 'Hand'
      'I': 'Current (electrical)'
      'J': 'Power'
      'K': 'Time, time schedule'
      'L': 'Level'
      'M': 'User''s choice'
      'N': 'User''s choice'
      'O': 'User''s choice'
      'P': 'Pressure, vacuum'
      'Q': 'Quantity '
      'R': 'Radiation'
      'S': 'Speed, frequency'
      'T': 'Temperature'
      'U': 'Multivariable'
      'V': 'Vibration, mechanical analyses'
      'W': 'Weight, force'
      'X': 'Unclassified'
      'Y': 'Event, state or presence'
      'Z': 'Position, dimension'

    # Modifiers
    modifier:
      'D': 'Differential'
      'F': 'Ration (fraction)'
      'J': 'Scan'
      'K': 'Time rate of change'
      'M': 'Momentary'
      'Q': 'Integrate, totalizer'
      'Z': 'Safety (SIL rated)'

    # Readout or Passive Functions
    readout_function:
      'A': 'Alarm'
      'B': 'User''s choice'
      'E': 'Sensor (primary element)'
      'G': 'Glass, viewing device'
      'I': 'Indication'
      'L': 'Light'
      'N': 'User''s choice'
      'O': 'Orifice, restriction'
      'P': 'Point (test connection)'
      'R': 'Record'
      'U': 'Multifunction'
      'W': 'Well'
      'X': 'Unclassified'

    # Output Functions
    output_function:
      'B': 'User''s choice'
      'C': 'Control'
      'K': 'Control Station'
      'N': 'User''s choice'
      'S': 'Switch'
      'T': 'Transmit'
      'U': 'Multifunction'
      'V': 'Valve, damper, louver'
      'X': 'Unclassified'
      'Y': 'Relay, compute, convert'
      'Z': 'Driver, actuator'

    # Modifier Functions
    modifier_function:
      'B': 'User''s choice'
      'H': 'High'
      'HH': 'High high'
      'L': 'Low'
      'LL': 'Low low'
      'M': 'Middle, intermediate'
      'N': 'User''s choice'
      'U': 'Multifunction'
      'X': 'X-axis'
      'Y': 'Y-axis'
      'Z': 'Z-axis'