# Do not change the indices! Insert any new element at the end.
# The index is saved in the tag table enum, changing the index of a type will change all existing tags.
# One designation for each type of tag requiring a data sheet. Name must be the model class name.
tagable:
  # electrical
  - Switchboard
  - Cable
  - Motor
  - SocketCct
  - LightCct
  # piping
  - Pipe
  - Source
  - Consumer
