roles:

  # Global roles (not tied to a specific resource)
  global_roles:
    - admin
    - app_owner

  # Resource-specific role definitions
  resources:
    project:
      - project_owner
      - team_member
    tag:
      - editor

    
  functional_roles:
    - electrical_designer
    - mechanical_designer
    - structural_designer
    - document_controller
  
