roles:

  # Global roles (not tied to a specific resource)
  global_roles:
    - admin
    - app_owner
    - document_controller
  # Resource-specific role definitions
  resources:
    project:
      - project_manager
      - project_admin
      - team_member
      - document_controller
    discipline:
      - designer
      - checker
      - approver
      - controller
      - custodian
      - document_controller
