# One designation for each type of tag requiring a data sheet. Name must be the Module::Model full class name.
tagable:
  # Electrical
  - Electrical::Switchboard
  - Electrical::Cable
  - Electrical::Motor
  - Electrical::SocketCct
  - Electrical::LightCct
  # Piping
  - Piping::Pipe
  - Piping::Source
  - Piping::Consumer
