default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: test_bench_development

test:
  <<: *default
  database: test_bench_test

production:
  <<: *default
  database: test_bench_production